#!/usr/bin/env php
<?php

/**
 * Shy Framework Console Entry
 *
 * @author    lynn<admin@lynncho.cn>
 * @link      http://lynncho.cn/
 */

define('SHY_START', microtime(true));

/**
 * Composer Autoload
 */
require __DIR__ . '/vendor/autoload.php';

/**
 * Helpers
 */
require __DIR__ . '/shy/core/function/helpers.php';

/**
 * Framework Run
 */

use shy\core\container;
use shy\console\exception\handler;

$_container = new container();
$_container->setExceptionHandler(new handler());
shy('console', 'shy\console')->run();
