#!/usr/bin/env php
<?php
/**
 * Shy Framework Console Entry
 *
 * @author    lynn<admin@lynncho.cn>
 * @link      http://lynncho.cn/
 */

/**
 * Composer autoload
 */
require __DIR__ . '/vendor/autoload.php';

/**
 * Bootstrap
 */
require __DIR__ . '/bootstrap/console.php';

/**
 * Run CLI mode
 */

shy('console')->run();
