#!/usr/bin/env php
<?php

/**
 * Shy Framework Console Entry
 *
 * @author    lynn<admin@lynncho.cn>
 * @link      http://lynncho.cn/
 */

define('SHY_START', microtime(true));

/**
 * Composer Autoload
 */
require_once __DIR__ . '/vendor/autoload.php';

/**
 * Helpers
 */
require_once __DIR__ . '/shy/function/helpers.php';

/**
 * Framework Run
 */

use shy\core\container;
use shy\console\exception\handler;
use shy\console;

$_container = new container();
$_container->setExceptionHandler(new handler(), config('env'));
$_container->bindObjectAndReturn('console', new console())->run();
